import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import "./globals.css";
import Header from "@/components/Header"; // path depends on your file structure
import { Jost } from 'next/font/google';

export const myFont = Jost({
  subsets: ['latin'],
  weight: ['400','500','700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={myFont.className}>
      <body className="antialiased">
        <StackProvider app={stackServerApp}>
          <StackTheme>
            <div className="relative min-h-screen overflow-hidden">
              {/* Background Pattern */}
              <div className="fixed inset-0 -z-10">
                <div
                  className="absolute top-1/2 left-1/2 h-[300px] w-[300px] animate-pulse rounded-full bg-gradient-to-br from-pink-400 via-orange-300 to-yellow-200 opacity-70 blur-3xl"
                  aria-hidden="true"
                />
              </div>

              {/* Foreground Content */}
              <Header />
              <main className="pt-12 md:pt-20 ">
                {children}
              </main>
            </div>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
