import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import "./globals.css";
import Header from "@/components/Header";
import { GridPatternDashed } from "@/components/GridPatternDashed";
import PointerWrapper from "@/components/PointerWrapper"; // path depends on your file structure

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <StackProvider app={stackServerApp}>
          <StackTheme>
            <PointerWrapper className="fill-blue-500" />
            <div className="relative min-h-screen overflow-hidden">
              {/* Background Pattern */}
              <div className="absolute inset-0 -z-10">
                <GridPatternDashed />
              </div>

              {/* Foreground Content */}
              <Header />
              <main className="pt-12 md:pt-20 px-8 md:px-16">
                {children}
              </main>
            </div>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
